### ISSUE TITLE
Boton "Ayuda" sin accion

### ISSUE THREAD

**Issue by Matias-L** [zimmcl/IngSoft-2016-SeDiceAtomico#12]
#### **Proyecto**:CintaMatrix300                    

**Nombre:** Matias Lionel Ceballos

**Severidad: Bajo**

**Fecha**: 11/06/2016

---

#### Descripción detallada del fallo:
El botón "Ayuda" ubicado en el menú de la aplicación no realiza ninguna acción al momento de presionarlo.

---
####  Forma de reproducirlo:
 1. Seleccionar `Ayuda`
 2. Seleccionar `Contenido de ayuda`

---
####  Segmento de código (opcional):
No aplica

---

**Comment by zimmcl** [comment]
Se edito para respetar formato
