### ISSUE TITLE
Agregar barra de progreso

### ISSUE THREAD

**Issue by Matias-L** [zimmcl/IngSoft-2016-SeDiceAtomico#6]

**Comment by Matias-L** [comment]
#### **Proyecto**:                    

**Solicitante del Cambio:** "Matias Lionel Ceballos"
**Lider del Proyecto: "Nombre"**
**Remitido a:** "Nombre"
**Fecha**: 11/06/2016

---

#### Cambio Solicitado:
Se solicita agregarle una barra de metros recorridos a la vista "CintaMatrix".
La misma debe estar configurada de forma tal que:
*Se complete a los 400 metros recorridos
*Una vez completada, se reinicie y continue su funcionamiento

--
####  Impacto en el Sistema:
No modifica el comportamiento del sistema.

--
####  Beneficio del Cambio:
Mejora la presentacion de datos al usuario

--
####  Costo del Cambio:
10 U$D

--

--

---

**Comment by zimmcl** [comment]
#### **Proyecto**:                    

**Solicitud asociada:** [#6](https://huboard.com/zimmcl/IngSoft-2016-SeDiceAtomico/#/issues/159799308)  **Fecha**: 11/06/2016

**Solicitante del Cambio: Matias Lionel Ceballos**

**Lider del Proyecto:** "Nombre"

**Aprobado por:** Zimmel Ezequiel

**Tiempo estimado:** 3hs

**Costo estimado:** 12U$D

**Fecha aprobación:** 12/06/2016


---

#### Descripción del cambio a realizar:
Se agregará a la vista "CintaMatrix" una barra que muestre la progresión de los metros recorridos.
La misma se configurará de forma tal que:

 * Se complete al valor ingresado mediante interfaz gráfica por el usuario, considerándose como metros a recorrer.
 * Una vez completada, se reinicie y continué su funcionamiento

---
####  Restricciones del cambio:
La barra de progreso deberá adoptar una orientación horizontal

---
####  Componentes a los que afecta el cambio:
 JDialog app

JPanel container

---
####  Documentación Auxiliar (opcional):
No aplica

---

**Comment by zimmcl** [comment]
Se implemento barra de progreso en SccView
